tab = int(input ('Qual a tabuada que você quer ver?'))
num = tab * 1
numm = tab * 2
nummm = tab * 3
nummmm = tab * 4
nummmmm = tab * 5
i = tab * 6
ih = tab * 7
ihh = tab * 8
ihhh = tab * 9
ihhhh = tab * 10
print ('1 x {} = {}'.format (tab, num))
print (' 2 x {} = {}'. format (tab, numm))
print (' 3 x {} = {}' .format (tab, nummm))
print ('4 x {} = {}' . format(tab, nummmm))
print ('5 x {} = {}' .format (tab, nummmmm))
print ('6 x {} = {}' .format (tab, i))
print ('7 x {} = {}' .format (tab, ih))
print ('8 x {} = {}' .format (tab, ihh ))
print ('9 x {} = {}'.format (tab, ihhh))
print ('10 x {} = {}' .format (tab, ihhhh))