a = (input ('Qual o seu nome?'))
print('O tipo primitivo desse valor é:', type(a))
print('Só tem espaço nessa mensagem?', a.isspace())
print('Essa mensagem é um número?', a.isnumeric())
print('Essa mensagem tem letra e número?', a.isalnum())
print('Essa mensagem está em caixa alta??', a.isupper())
print(a.isdigit())
